version: '2'
services:
  storagemanagementspring-app:
    image: storagemanagementspring
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://storagemanagementspring-postgresql:5432/storageManagementSpring
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://storagemanagementspring-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://storagemanagementspring-elasticsearch:9200
    ports:
      - 8080:8080
  storagemanagementspring-postgresql:
    extends:
      file: postgresql.yml
      service: storagemanagementspring-postgresql
  storagemanagementspring-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: storagemanagementspring-elasticsearch
